---
- include: setup.yml

- name: enable production mode
  become: yes
  hostname:
    name: master
  when: production
  register: production_mode

- name: Make my directory tree readable
  become: yes
  file:
    path: /usr/share/openitcockpit
    owner: www-data
    group: www-data
    mode: 0774
    recurse: yes

- name: Ensure that Cache folder ist present and writeable
  file:
    path: /usr/share/openitcockpit/app/tmp/
    state: directory
    owner: www-data
    group: www-data
    mode: 0777
    recurse: yes

- name: Ensure that Log-Cache folder ist present and writeable
  file:
    path: /usr/share/openitcockpit/app/tmp/logs/
    state: directory
    owner: www-data
    group: www-data
    mode: 0777
    recurse: yes


- name: Ensure error-log files are present and writeable
  file:
    path: /usr/share/openitcockpit/app/tmp/logs/error.log
    state: touch
    owner: www-data
    group: www-data
    mode: 0777

- name: set setup wrapper
  become: yes
  template:
    src: setup_wrapper.sh.j2
    dest: /usr/share/openitcockpit/setup_wrapper.sh
    owner: root
    group: root
    mode: 700

- name: start setup wrapper
  become: yes
  command: /usr/share/openitcockpit/setup_wrapper.sh
  when: (setup_packages.changed or production_mode.changed)